steps:
- name: 'ubuntu'
  args: ['bash', './myscript.bash']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/test-gcp-cloud-builder', '.']
images: ['gcr.io/$PROJECT_ID/test-gcp-cloud-builder']
